version: "3"
services:
  clickhouse:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: yandex/clickhouse-server
    ports:
    - "8123:8123"
    - "9000:9000"
    - "9001:9001"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
